repos:
  # https://docs.astral.sh/uv/guides/integration/pre-commit/
  # To make sure your uv.lock file is up to date even if your pyproject.toml file was changed:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.7.19
    hooks:
      - id: uv-lock
  # To keep a requirements.txt file in sync with your uv.lock file:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.7.19
    hooks:
      - id: uv-export
  # use ruff for linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
    rev: v0.12.2
    hooks:
      # Run the linter.
      - id: ruff-check
      # Run the formatter.
      - id: ruff-format